import { app, BrowserWindow, ipcMain } from "electron";
import path from "path";
import { execFile, ChildProcess, type ExecFileOptions } from "child_process";
import squirrelCheck from "@/squirrel-check";
import net from "net";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (squirrelCheck()) {
  app.quit();
}

let javaProcess: ChildProcess;

async function getFreePort() {
  return new Promise<number | undefined>((res) => {
    const srv: net.Server = net.createServer();
    srv.listen(0, () => {
      let port: number | undefined = undefined;
      const address = srv.address();
      if (address && typeof address === "object") {
        port = address.port;
      }
      srv.close(() => res(port));
    });
  });
}

const createWindow = async () => {
  const mainWindow = new BrowserWindow({
    width: 1920,
    height: 1080,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  });

  const port = await getFreePort();

  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`));

    const exePath = path.resolve(app.getAppPath(), "../endpoint-desktop");

    javaProcess = execFile(exePath, {
      env: {
        WHITE_RABBIT_PORT: port,
        WHITE_RABBIT_PASSWORD: "server-password user-password",
      },
    } as ExecFileOptions);
  }

  mainWindow.webContents.openDevTools();

  ipcMain.handle("get-port", () => {
    return port;
  });
};

app.on("ready", createWindow);

app.on("window-all-closed", () => {
  javaProcess?.kill();

  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", async () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    await createWindow();
  }
});
