spring:
  datasource:
    url: jdbc:h2:file:./data;CIPHER=AES;AUTO_SERVER=TRUE
    username: username
    password: ${WHITE_RABBIT_PASSWORD:password password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  threads:
    virtual:
      enabled: true
server:
  port: ${WHITE_RABBIT_PORT:8080}
