spring:
  datasource:
    url: jdbc:h2:file:./data;CIPHER=AES;AUTO_SERVER=TRUE
    username: username
    password: ${WHITE_RABBIT_PASSWORD:password password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  threads:
    virtual:
      enabled: true
server:
  port: ${WHITE_RABBIT_PORT:8080}
springdoc:
  default-produces-media-type: application/json
app:
  hateoas:
    base-url: http://localhost:${WHITE_RABBIT_PORT:8080}
management:
  endpoints:
    web:
      cors:
        allowed-origin-patterns: http://127.0.0.1:*,http://localhost:*
        allowed-methods: GET
logging:
  file:
    name: endpoint-desktop.log
