spring:
  datasource:
    url: jdbc:h2:file:./data;CIPHER=AES;AUTO_SERVER=TRUE
    username: username
    password: password password
  jpa:
    hibernate:
      ddl-auto: create
  threads:
    virtual:
      enabled: true
