spring:
  datasource:
    url: jdbc:h2:file:./white-rabbit;AUTO_SERVER=TRUE;CIPHER=AES
    username: whiterabbit
    password: whiterabbit test1234
  jpa:
    hibernate:
      ddl-auto: validate
  graphql:
    graphiql:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://white-rabbit-dev.authing.cn/oidc
